hmcts/vh-infra-wowza

- pipeline-steps/terraform-apply.yaml
add unlock step
```
[ ] Yes
[ x ] No
```
> VIH-9999 - add unlock step

- terraform/10-video-hearing-wowza/modules/wowza/network.tf
Change NSG Rules from Nested to Individual Resource Blocks
```
[ ] Yes
[ x ] No
```
> VIH-9999 - Change NSG Rules from Nested

- terraform/10-video-hearing-wowza/modules/wowza/wowza_lb_alerts.tf
VIH-9603 
VIH-9603 - Amend LB alert
```
[ ] Yes
[ x ] No
```
> VIH-9603 - Amend LB alert

- azure-pipelines.yaml
- terraform/10-video-hearing-wowza/modules/wowza/automation_account.tf
- terraform/10-video-hearing-wowza/modules/wowza/wowza_lb_alerts.tf
VIH-9605 - add dynatrace runbook
VIH-9605 - add dynatrace runbook
```
[ ] Yes
[x ] No
```
> VIH-9605 - add dynatrace runbook

- azure-pipelines.yaml
- config/pipeline/vars/wowza/demo.yaml
- config/terraform/application/vars/demo.tfvars
- config/terraform/application/vars/dev.tfvars
- config/terraform/application/vars/ithc.tfvars
- config/terraform/application/vars/sbox.tfvars
- config/terraform/application/vars/test.tfvars
- pipeline-steps/check-state.yaml
VIH-9642 - Add Demo Env
VIH-9642 - Add Demo Env
```
[ ] Yes
[ x ] No
```
> VIH-9642 - Add Demo Env

- terraform/10-inputs-required.tf
- terraform/20-main.tf
VIH-9999 - FIX: add input
VIH-9999 - FIX: add input
```
[ ] Yes
[ x ] No
```
> VIH-9999 - FIX add input

- config/terraform/application/vars/demo.tfvars
VIH-9999 - Add IP Address for Demo Wowza
VIH-9999 - Add IP Address for Demo Wowza
```
[ ] Yes
[ x ] No
```
> VIH-9999 - Add IP Address for Demo Wowza

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/renovate.json
- .github/stale.yml
- .gitignore
- renovate.json
https://tools.hmcts.net/jira/browse/VIH-9643?filter=-1
close stale PRs either merge or close
add the stale.yml
add PR title validation
add renovate.json
add dependatbot.yml
add PULL_REQUEST_TEMPLATE.md
add ISSUE_TEMPLATE.md
add CONTRIBUTING.md
Enforce Admins cannot bypass on PR branch
Delete branch on PR close
add .gitignore
```
[ ] Yes
[X ] No
```
> VIH-9643 GitHub health check clean

- azure-pipelines.destroy.yaml
- templates/terraform-plan-apply.yaml
- templates/terraform-plan.yaml
VIH-9676 - Add Destroy Support
VIH-9676 - Add Destroy Support
```
[ ] Yes
[x  ] No
```
> VIH-9676 - Add Destroy Support

- terraform/infra/network-security-group.tf
VIH-9691 - Add NSG rule for Private Endpoint
VIH-9691 - Add NSG rule for Private Endpoint
```
[ ] Yes
[x  ] No
```
> VIH-9691 - Add NSG rule for Private Endpoint

- terraform/infra/diagnostic-settings.tf
VIH-9999 - re enable diag settings
```
[ ] Yes
[ x ] No
```
> VIH-9999 - re enable diag settings

- terraform/infra/automation-account-runbook.tf
- terraform/infra/load-balancer-alerts.tf
- vars/terraform/dev.tfvars
VIH-9617 - Add Dynatrace Webhook
VIH-9617 - Add Dynatrace Webhook
```
[ ] Yes
[ x ] No
```
> VIH-9617 - Add Dynatrace Webhook

- terraform/infra/cloudconfig.tpl
VIH-9999 - amend missed closing quote
```
[ ] Yes
[ ] No
```
> VIH-9999 - amend missed closing quote

- azure-pipelines.yaml
N/A
Add ITHC environment to VH
```
[ ] Yes
[X ] No
```
> VIH-9999 Add ITHC

- terraform/infra/key-vault-secrets.tf
VIH-0000 - add connection string secret
VIH-0000 - add connection string secret
```
[ ] Yes
[  x ] No
```
> VIH-0000 - add connection string secret

- vars/terraform/ithc.tfvars
https://tools.hmcts.net/jira/browse/VIH-9778
Add address_space variable for Ithc environment
```
[ ] Yes
[ X] No
```
> VIH-9778 Add address_space for ITHC env

- vars/terraform/ithc.tfvars
https://tools.hmcts.net/jira/browse/VIH-9778
Add more network values for ithc environment
```
[ ] Yes
[X ] No
```
> VIH-9778 Add more network values for ithc

- vars/terraform/demo.tfvars
https://tools.hmcts.net/jira/browse/VIH-9790
Reduce wowza to 1 vm in demo environment
```
[ ] Yes
[X ] No
```
> VIH-9790 Reduce Demo wowza vms to 1

- azure-pipelines.yaml
- terraform/infra/storage-account.tf
- vars/pipeline/test.yaml
- vars/terraform/test.tfvars
https://tools.hmcts.net/jira/browse/VIH-9912
Re-add test environment
```
[ ] Yes
[x] No
```
> VIH-9912 add required environment

- terraform/infra/automation-account-start-stop-vm.tf
- vars/terraform/demo.tfvars
- vars/terraform/dev.tfvars
- vars/terraform/ithc.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
https://tools.hmcts.net/jira/browse/VIH-9945
Testing automation in sandbox environment 
```
[ ] Yes
[x] No
```
> VIH-9945 create automation

- terraform/infra/cloudconfig.tpl
- terraform/infra/virtual-machine.tf
[VIH-9954](https://tools.hmcts.net/jira/browse/VIH-9954)
Adding a line in the cert renew to restart the service if the cert is renewed.
```
[ ] Yes
[X] No
```
> VIH-9954 Add service restart

- terraform/infra/network-security-group.tf
https://tools.hmcts.net/jira/browse/VIH-9975
Pexip have provided a new list of public IPs that are to be allowed, 
```
[ ] Yes
[X] No
```
> VIH-9975 update pexip ips

- scripts/install-splunk-forwarder-service.sh
- templates/az-ext-splunk.yaml
- templates/terraform-plan-apply.yaml
- terraform/infra/cloudconfig.tpl
- terraform/infra/key-vault-secrets.tf
- terraform/infra/virtual-machine-cloudconfig.tf
- terraform/infra/virtual-machine-extension.tf
- terraform/infra/virtual-machine.tf
[VIH-9994](https://tools.hmcts.net/jira/browse/VIH-9994)
New wowza version
```
[ ] Yes
[X] No
```
> VIH-9994 New wowza version

- terraform/infra/virtual-network-peering.tf
https://tools.hmcts.net/jira/browse/VIH-9994
Remove part of local from virtual-network-peering.tf
```
[ ] Yes
[x] No
```
> VIH-9994 Remove ukw-hub-prod-int

- terraform/infra/_main.tf
- terraform/infra/managed-identity.tf
[VIH-9579](https://tools.hmcts.net/jira/browse/VIH-9579)
Adding rpa mi access to sa to allow reading and tagging of BLOBs
```
[ ] Yes
[X] No
```
> VIH-9579 Adding rpa mi access

- terraform/infra/_providers.tf
- terraform/infra/_variables.tf
- vars/terraform/demo.tfvars
- vars/terraform/prod.tfvars
[VIH-9579](https://tools.hmcts.net/jira/browse/VIH-9579)
```
[ ] Yes
[X] No
```
> VIH-9579 add sub

- azure-pipelines.yaml
- terraform/infra/_main.tf
- terraform/infra/_providers.tf
- terraform/infra/managed-identity.tf
VIH-9579 
```
[ ] Yes
[X] No
```
> VIH-9579  add provider

- vars/terraform/demo.tfvars
- vars/terraform/ithc.tfvars
https://tools.hmcts.net/jira/browse/VIH-10243
To save cost VMs in demo and ithc environment will stay off unless manually started
```
[ ] Yes
[x] No
```
> VIH-10243 Manually Start VM

- templates/terraform-plan-apply.yaml
- terraform/infra/_variables.tf
- terraform/infra/storage-account.tf
- vars/terraform/test.tfvars
> VIH-0000 add allow for tf

- terraform/infra/virtual-machine.tf
https://tools.hmcts.net/jira/browse/VIH-10274
Wowza have released a new version of Wowza marketplace image
```
[ ] Yes
[x] No
```
> VIH-10274 Update wowza version

- terraform/infra/_variables.tf
- terraform/infra/storage-account.tf
- terraform/infra/virtual-machine.tf
- vars/terraform/demo.tfvars
[VIH-9575](https://tools.hmcts.net/jira/browse/VIH-9575)
We need to configure a life cycle management policy in Azure blob storage to delete audio recordings from here. The policy will be based on the recordings age and the blob index flag added by HRS 
```
[ ] Yes
[X] No
```
> VIH-9575 add new var and lifecycle

- terraform/infra/diagnostic-settings.tf
[VIH-9577](https://tools.hmcts.net/jira/browse/VIH-9577)
Diagnostic logs are needed to provide insights into the the tasks performed on the blob storage which are needed for auditing purposes so we can see when the delete flag was applied or when the file was retrieved by someone.
```
[ ] Yes
[X] No
```
> VIH-9577 Update diagnostics

- azure-pipeline.vm-boot.yaml
- scripts/set-vmStatus.ps1
- vars/terraform/dev.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
[VIH-10305](https://tools.hmcts.net/jira/browse/VIH-10305)
- Create a pipeline to allow users to select the number of Wowza VMs that run in an environment
- Update schedule to turn off all Wowza VMs at 19:00
```
[ ] Yes
[X] No
```
> VIH-10305 Reduce wowza usage

- terraform/infra/_main.tf
- terraform/infra/_variables.tf
- terraform/infra/_versions.tf
- terraform/infra/diagnostic-settings.tf
- terraform/infra/storage-account.tf
- terraform/infra/virtual-machine.tf
- vars/terraform/dev.tfvars
- vars/terraform/ithc.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
[VIH-10305](https://tools.hmcts.net/jira/browse/VIH-10305)
Adding var to set smaller OS disk sizes to non-prod
```
[ ] Yes
[ ] No
```
> VIH-10305 add disk size for envs

- terraform/infra/_variables.tf
- terraform/infra/storage-account.tf
- vars/terraform/dev.tfvars
- vars/terraform/prod.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
https://tools.hmcts.net/jira/browse/VIH-10368
Currently soft delete retention period is set as default to 365 days, we need to change this for each environment
```
[ ] Yes
[x] No
```
> VIH-10368 sbox-retention

- azure-pipeline.vm-boot.yaml
https://tools.hmcts.net/jira/browse/VIH-10448
Spelling mistake within a vh pipeline that needed fixing
```
[ ] Yes
[x] No
```
> VIH-10448 Fix-Mistake

- templates/az-ext-dynatrace-api.yaml
> VIH-0000 Update az-ext-dynatrace-api.yaml

- templates/terraform-plan-apply.yaml
> VIH-0000 Removing splunk

- templates/az-ext-oms.yaml
> VIH-0000 Update az-ext-oms.yaml

- templates/az-ext-splunk.yaml
- templates/terraform-plan-apply.yaml
> VIH-0000 Json fix

- azure-pipeline.vm-boot.yaml
https://tools.hmcts.net/jira/browse/VIH-10471
Currently one of the parameters for vm boot is set to 0,1 and 2. This needs amending to take out the 0 as it is not required
```
[ ] Yes
[ x] No
```
> VIH-10471 Fix-vm-boot

- terraform/infra/route-table.tf
- terraform/infra/virtual-network.tf
https://tools.hmcts.net/jira/browse/VIH-10917
There are some changes in the code that needs to be amended which are currently out dated.
```
[ ] Yes
[ x] No
```
> VIH-10917 Code fix

- vars/terraform/demo.tfvars
https://tools.hmcts.net/jira/browse/VIH-10938
Adding in schedule for demo env to turn on vm at 8am everyday
```
[ ] Yes
[ x] No
```
> VIH-10938 Demo vm-on

- terraform/infra/_variables.tf
- terraform/infra/virtual-machine.tf
- vars/terraform/demo.tfvars
- vars/terraform/ithc.tfvars
- vars/terraform/prod.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
https://tools.hmcts.net/jira/browse/VIH-10980
Enables Wowza VMs in Test and Stg environments to automatically power on each morning.
```
[ ] Yes
[X] No
```
> VIH-10980 enabled power on schedule for test & stg wowza vms

- terraform/infra/_providers.tf
https://tools.hmcts.net/jira/browse/VIH-11009
Fix prod plan issue
```
[ ] Yes
[x ] No
```
> VIH-11009 prod fix

- vars/terraform/prod.tfvars
https://tools.hmcts.net/jira/browse/VIH-11009
Change prod image to required version
```
[ ] Yes
[x ] No
```
> VIH-11009 Change prod image

- terraform/infra/_providers.tf
- terraform/infra/_versions.tf
https://tools.hmcts.net/jira/browse/VIH-11027
Remove the skip registration within the vh-infra-wowza dir and implement a new azure rm version
```
[ ] Yes
[x ] No
```
> VIH-11027 update azurerm version

- templates/az-ext-dynatrace-api.yaml
JIRA link (if applicable)
[https://tools.hmcts.net/jira/browse/VIH-11080](https://tools.hmcts.net/jira/browse/VIH-11080)
> VIH-11080 fix incorrectly changed var

- templates/terraform-plan-apply.yaml
- vars/pipeline/demo.yaml
- vars/pipeline/dev.yaml
- vars/pipeline/ithc.yaml
- vars/pipeline/sbox.yaml
- vars/pipeline/stg.yaml
- vars/pipeline/test.yaml
https://tools.hmcts.net/jira/browse/VIH-11080
Adds Test environment to Dynatrace extension install step, and sets appropriate Host Groups for non-prod envs.
```
[ ] Yes
[x] No
```
> VIH-11080 add test to wowza vm dynatrace extension task

- terraform/infra/_variables.tf
- terraform/infra/automation-account-start-stop-vm.tf
- vars/terraform/demo.tfvars
https://tools.hmcts.net/jira/browse/VIH-11172
Apply VH Wowza VM automation schedule to individual VMs
```
[ ] Yes
[x] No
```
> VIH-11172 - apply VH Wowza VM automation schedule to individual VMs

- vars/terraform/demo.tfvars
https://tools.hmcts.net/jira/browse/VIH-11198
Re-adds both Demo Wowza VMs to nightly auto-shutdown schedule
```
[ ] Yes
[x] No
```
> VIH-11198 re-enable auto-shutdown for demo wowza vms

- terraform/infra/cloudconfig.tpl
https://tools.hmcts.net/jira/browse/VIH-11218
updated cert renew script to use cert alias during Java Keystore import process
```
[ ] Yes
[X] No
```
> VIH-11218 updated cert renew script to use cert alias

- vars/terraform/demo.tfvars
- vars/terraform/dev.tfvars
- vars/terraform/ithc.tfvars
- vars/terraform/prod.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
https://tools.hmcts.net/jira/browse/VIH-10798
Add SS AKS subnets to Wowza storage account firewall
```
[ ] Yes
[x] No
```
> VIH-10798 enable private storage networking

- terraform/infra/storage-account.tf
- vars/terraform/prod.tfvars
> VIH-10798 allow public access to prod only

- terraform/infra/_variables.tf
- terraform/infra/storage-account.tf
- vars/terraform/demo.tfvars
- vars/terraform/dev.tfvars
- vars/terraform/ithc.tfvars
- vars/terraform/prod.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
https://tools.hmcts.net/jira/browse/VIH-10798
Adds GlobalProtect & AnyConnect VPN egress IPs to Wowza storage firewalls
> VIH-10798 add vpn egress IP ranges to vh wowza storage firewall

- vars/terraform/prod.tfvars
https://tools.hmcts.net/jira/browse/VIH-10798
Set default action to Deny for Prod storage firewall for [CHG5019718](https://mojcppprod.service-now.com/nav_to.do?uri=%2Fchange_request.do%3Fsys_id%3D9aba9ae91b1b1a10923afb25464bcbc9)
> VIH-10798 set prod storage firewall to private

- terraform/infra/_main.tf
- terraform/infra/managed-identity.tf
- terraform/infra/resource-group.tf
- terraform/infra/storage-account.tf
https://tools.hmcts.net/jira/browse/VIH-11268
Adds Contributor role assignment to "DTS VH Contributor (env:prod)" group
Adds Storage Blob Data Contributor role assignment to "DTS VH Wowza Storage Blob Data Reader (env:prod)" group
```
[ ] Yes
[x] No
```
> VIH-11268 Add role assignments to resource group and storage to map to groups

- azure-pipelines.yaml
- vars/pipeline/common.yaml
- vars/pipeline/prod.yaml
https://tools.hmcts.net/jira/browse/VIH-11267
Currently when we deploy to Prod in VH, it goes through deploying each environment. We want the process to only deploy to prod, if a specific branch such as release/ is defined
```
[ ] Yes
[x] No
```
> VIH-11267 Prod branch

- vars/terraform/prod.tfvars
https://tools.hmcts.net/jira/browse/VIH-11285
Reverts merge to master made before release branch created & deployed.
> VIH-11285 re-add_aks_subnets_to_prod_storage_firewall

- templates/azure-devops-vars.yaml
- terraform/infra/cloudconfig.tpl
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=312&view=detail&selectedIssue=VIH-11341
Update script to use --client-id
```
[ ] Yes
[ x] No
```
> VIH-11314 update script

- templates/azure-devops-vars.yaml
Update references to devops variable groups
> VIH-0000 Update references to var groups

- terraform/infra/_variables.tf
https://tools.hmcts.net/jira/browse/VIH-11364
Update wowza vm version
```
[ ] Yes
[x ] No
```
> VIH-11364 update wowza version

- vars/terraform/demo.tfvars
- vars/terraform/dev.tfvars
- vars/terraform/ithc.tfvars
- vars/terraform/prod.tfvars
- vars/terraform/sbox.tfvars
- vars/terraform/stg.tfvars
- vars/terraform/test.tfvars
VIH-10798
Adds Azure DevOps agent outbound IP address ranges
> VIH-10798 add Azure DevOps agent outbound IP address ranges

- vars/terraform/prod.tfvars
https://tools.hmcts.net/jira/browse/VIH-11403
Remove prod route
```
[ ] Yes
[ x] No
```
> VIH-11403 rm-prod-route

- terraform/infra/private-dns.tf
https://tools.hmcts.net/jira/browse/VIH-11410
correct naming of vnet link
> VIH-11410 correct naming of vnet link

- terraform/infra/_variables.tf
- terraform/infra/automation-account-start-stop-vm.tf
- vars/terraform/prod.tfvars
https://tools.hmcts.net/jira/browse/VIH-11416
Prod is currently costing a lot when not in use, hence need to shut it down.
```
[ ] Yes
[x] No
```
> VIH-11314 prod vm schedule to off everyday if turned on

- vars/terraform/prod.tfvars
> VIH-10798 fix prod vars
